### ISSUE TITLE
model.merge

### ISSUE THREAD

**Issue by eloyleonardo** [brikteknologier/seraph-model#100]
Why merge operation isn't available ? 
In the write.js have a task to do that, but it isn't expose in the model, has another way i can do that ? 

My problem is, i have a composition, in same cases i need to save all items, and in same cases if the item already exists i like to just make the relationship (not update the target node). Has another way to do that ? 
Thanks

**Comment by jonpacker** [comment]
If I'm understanding you correctly, this is a different issue to #103? I'm not entirely sure what you mean by making a new relationship if the item already exists. Is it such that you want to save a new relationship to a node that is already composed on your model, so that the node is composed twice?

**Comment by jonpacker** [comment]
Maybe it would help if you could give me some examples of what you want to be able to do :)

**Comment by jonpacker** [comment]
Going to assume that this is covered by #103.
